repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--check]

  - repo: local
    hooks:
      - id: ty-check
        name: ty-check
        entry: uv run ty check proxmox_openapi tests --output-format concise
        language: system
        pass_filenames: false
